vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.26:mtMkjJrLDD5C2eLocxpWzg==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
    - Equinusocio.vsc-material-theme@30.0.0:PskT49UZHjppd3FhLdFvtg==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==